# Generated by Django 5.0 on 2024-01-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created', '-updated')},
        ),
    ]
