# Generated by Django 5.0 on 2024-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
