# Generated by Django 5.0 on 2024-02-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='createt_at',
            new_name='created_at',
        ),
    ]
